### ISSUE TITLE
언어 테이블 논의

### ISSUE THREAD

**Issue by mijien0179** [cacaocoffee/OSS#14]
table: language
|column name  | data type  |NULL         |option              | desc                      |
|:--------------- |-----------  |-------------|-----------------|-------------------|
|userid              |int unsigned| NOTNULL | PRIMARY KEY |user테이블 id      |
|language         |varchar(16)  | NOTNULL | PRIMARY KEY | 사용 언어            |

_Originally posted by @cacaocoffee in https://github.com/cacaocoffee/OSS/issues/12#issuecomment-962444426_

**Comment by mijien0179** [comment]
column에 값을 고정적으로 언어를 넣어버리면 나중에 언어나 스택이 새로 추가될 때 처리하기가 힘들어서 위와 같이 언어 이름 자체를 저장할 수 있도록 하고 거기서 값을 찾도록 하는게 좋을것 같습니다.

**Comment by cacaocoffee** [comment]
넵 이해했습니다 그렇게 찾아볼게요

**Comment by mijien0179** [comment]
언어 이름은 고정적으로 하기 위해서 언어/스택 목록 테이블을 따로 구성하는 것도 좋겠군요. 그렇게 하면
* 언어 테이블 -> 사용자 언어 테이블
* **new** 언어 목록 테이블
이런식으로 테이블명을 바꿔야할것같네요.

**Comment by cacaocoffee** [comment]
사용자 언어 테이블
table: language_user
|column name  | data type  |NULL         |option              | desc                      |
|:--------------- |-----------  |-------------|-----------------|-------------------|
|userid              |int unsigned| NOTNULL | PRIMARY KEY |user테이블 id      |
|language         |char(16)  | NOTNULL | PRIMARY KEY | 사용 언어            |

언어 목록테이블
table: language_list
|column name  | data type  |NULL         |option              | desc                      |
|:--------------- |-----------  |-------------|-----------------|-------------------|
|C       |TINYINT(1)| NOTNULL | | C 언어 사용가능여부           |
|C++       |TINYINT(1)| NOTNULL | | C++ 언어  사용가능여부           |
|C#      |TINYINT(1)| NOTNULL | | C#  사용가능여부           |
|HTML      |TINYINT(1)| NOTNULL | | HTML 사용가능여부           |
|CSS       |TINYINT(1)| NOTNULL | | CSS  사용가능여부           |
|JS     |TINYINT(1)| NOTNULL | | javascript 사용가능여부           |

이런 방식 말씀하신건가요?

**Comment by mijien0179** [comment]
다른 문제가 있는 경우 새로운 이슈로 작성 바람
