### ISSUE TITLE
프로젝트 테이블 논의

### ISSUE THREAD

**Issue by cacaocoffee** [cacaocoffee/OSS#26]
## 프로젝트 테이블
table:  project
| Column Name | Comment           | data type       | Default     | NULL        | Option            |
|-----------------:|:------------------|:---------------|:------------|:------------|:----------------|
| id                     | 프로젝트     식별아이디      | int unsigned |       -           | NOT NULL | PRIMARY KEY |
| name          | 프로젝트이름 |  tinytext(20)    |       -          | NOT NULL |  |
| description               | 프로젝트 설명 | text    |       -           |  NULL |                  |
|deadline| 프로젝트 종료기간 |  date| NOT NULL | |

## 프로젝트 명단 테이블
table:  project_user
| Column Name | Comment           | data type       | Default     | NULL        | Option            |
|-----------------:|:------------------|:---------------|:------------|:------------|:----------------|
|userid                     | 유저아이디      | int unsigned |       -           | NOT NULL | FOREIGN KEY |
| projectid          | 프로젝트아이디 |  int unsigned    |       -          | NOT NULL |  FOREIGN KEY|

##프로젝트 언어 테이블
table: language_project
| Column Name | Comment           | data type       | Default     | NULL        | Option            |
|-----------------:|:------------------|:---------------|:------------|:------------|:----------------|
| languageid          | 사용언어식별아이디      | int unsigned |       -           | NOT NULL | FOREIGN KEY language_list(id)|
| projectid        | 프로젝트식별아이디 |  int unsigned    |       -          | NOT NULL | FOREIGN KEY project(id) |

**Comment by mijien0179** [comment]
다른 문제가 있는 경우 새로 이슈를 열기 바람
Close #26
