### ISSUE TITLE
프로젝트 생성자 추가 필요

### ISSUE THREAD

**Issue by mijien0179** [cacaocoffee/OSS#36]
프로젝트 테이블 작성할 때 생성한 회원(프로젝트 팀장의 개념) id값을 저장하는 컬럼 추가 필요

**Comment by mijien0179** [comment]
추가로 `생성 일자에 대한 컬럼`도 추가하면 좋겠습니다. `mysql date auto insert`에 대한 내용으로 검색하면 나오는 것으로 보입니다.

**Comment by cacaocoffee** [comment]
넵 금방 만들겠습니다

**Comment by cacaocoffee** [comment]
## 프로젝트 테이블
table:  project
| Column Name | Comment           | data type       | Default     | NULL        | Option            |
|-----------------:|:------------------|:---------------|:------------|:------------|:----------------|
| id                     | 프로젝트     식별아이디      | int unsigned |       -           | NOT NULL | PRIMARY KEY |
|leaderid|프로젝트 팀장 id| int unsigned||NOT NULL| |
| name          | 프로젝트이름 |  tinytext(20)    |       -          | NOT NULL |  |
| description               | 프로젝트 설명 | text    |       -           |  NULL |                  |
|deadline| 프로젝트 종료기간 |  date| NOT NULL | |
|createtime|프로젝트 생성 기간 | data|CURRENT_TIMESTAMP | | |

## 프로젝트 명단 테이블
table:  project_user
| Column Name | Comment           | data type       | Default     | NULL        | Option            |
|-----------------:|:------------------|:---------------|:------------|:------------|:----------------|
|userid                     | 유저아이디      | int unsigned |       -           | NOT NULL | FOREIGN KEY |
| projectid          | 프로젝트아이디 |  int unsigned    |       -          | NOT NULL |  FOREIGN KEY|

##프로젝트 언어 테이블
table: language_project
| Column Name | Comment           | data type       | Default     | NULL        | Option            |
|-----------------:|:------------------|:---------------|:------------|:------------|:----------------|
| languageid          | 사용언어식별아이디      | int unsigned |       -           | NOT NULL | FOREIGN KEY language_list(id)|
| projectid        | 프로젝트식별아이디 |  int unsigned    |       -          | NOT NULL | FOREIGN KEY project(id) |

**Comment by mijien0179** [comment]
`deadline`과 `createtime`의 `comment`값 변경하긴 했는데 고대로 진행하셔도 좋을 듯 합니다.

**Comment by mijien0179** [comment]
@cacaocoffee 완료시 Closed #36 닫아주세요.
