### ISSUE TITLE
작성되어야 할 페이지 목록

### ISSUE THREAD

**Issue by mijien0179** [cacaocoffee/OSS#4]
* 로그인
* 회원가입
* 메인홈
* 개인 프로필
* 프로젝트

논의를 통해 위 목록에서 추가/수정/제거 필요

**Comment by mijien0179** [comment]
views 폴더에서 작성하기 바람.

**Comment by c0c0pang** [comment]
[로그인+회원가입.zip](https://github.com/cacaocoffee/OSS/files/7459433/%2B.zip)

**Comment by mijien0179** [comment]
완료 될 때까지 닫지 마세요

**Comment by mijien0179** [comment]
사이트 관리용 페이지가 추가되면 좋을것같은데요.. @c0c0pang @hyunjin0311

**Comment by mijien0179** [comment]
이슈가 열린지 오래 되어 닫습니다. 새로운 이슈나 관련 이슈는 새로 이슈 생성하기 바랍니다.
Closed #4
