### ISSUE TITLE
[API] 보안: 사용자 정보 로드 API에서 사용자 pw 노출

### ISSUE THREAD

**Issue by mijien0179** [cacaocoffee/OSS#48]
외부에서 api를 호출할 때 불필요한 pw가 노출됩니다. 해당 pw는 삭제하고 다른 데이터는 동일하게 반환하도록 코드를 수정바랍니다.
![image](https://user-images.githubusercontent.com/40613626/143197301-3c5fc30f-a7e3-43d9-9182-b2dd44ca1407.png)

**Comment by cacaocoffee** [comment]
해결!
