### ISSUE TITLE
프론트-백 데이터 전송 규약

### ISSUE THREAD

**Issue by mijien0179** [cacaocoffee/OSS#9]
# 전송 규약

## 사용자 관련

|프론트엔드에서|백엔드에서|
|-----------------------------|---------------------------|
|user-id | user_id |
|user-pw| user_pw|
|user-name| user_name|
|user-language-list|user_lang_list|
---------------------------------------------------------

> 위 내용은 form 에서 get/post 등의 전송을 할 때 name작성하는 내용, ajax에서도 위와 같은 방법으로

**Comment by cacaocoffee** [comment]
language- list는 사용자가 사용할 수 있는 언어

**Comment by mijien0179** [comment]
## 설치 페이지
|프론트에서|백엔드로|
|--------------------|--------------------------------|---------------------------------|
| dbHost | dbHost |
| dbId | dbId |
|

**Comment by mijien0179** [comment]
## 설치 페이지

| 대상 | 프론트-엔드 | 백-엔드  |
|----------:|--------|----------|
| 호스트    | dbHost | dbHost   |
| ID        | dbId   | dbId     |
| PW        | dbPassword | dbPassword|
| DB Name   | dbName| dbName|

**Comment by mijien0179** [comment]
그닥 불필요하고 사용 안 하는것 같아서 닫겠습니다.
Close #9
